### ISSUE TITLE
 Cannot read property 'rootid' of undefined

### ISSUE THREAD

**Issue by MikeSkril** [NDVM/NDVM#24]
I'm getting below error when adding a bigger video file collection. NDVM is walking quite some time thru the directory but not adding any files. Just resulting in the below error message.

```
[DEBUG] LIBRARY - ingest SQL statement built: 1995 lines
[DEBUG] DB/default - executing non-query with pipe
[DEBUG] TOOL - executing: sqlite3 ../data/db/default.sqlite
[DEBUG] SQLITE - retrieved 0 records.
ERROR: TypeError: Cannot read property 'rootid' of undefined
```

**Comment by hlechner** [comment]
Would be better if somehow I can reproduce the error.

Could you test if this error is caused by a specific video file or by the amount of it?

If it can be caused by specific file/files could be related to ffprobe verification.

I really appreciate any test results on your side, so it will be better to understand and also to solve the issue.

**Comment by MikeSkril** [comment]
Is there a way to get more log output? I mean beside adding 'debug' when starting.

**Comment by MikeSkril** [comment]
I did some testing... 2 problems. If there is a corrupt video file, debug will show a message 'invalid video file' and it seems that 'walker' will not continue after that.

The other issue seems to be related to the number of files. To reproduce you can create a folder with a few sub folders in it, putting like 60 video files in every sub folder. Now try to browse the folder, when you click on the plus symbol, it'll keeps spinning a long time before you can browse the folder. Sometimes 'walker' seemed to have died and not going on anymore.

**Comment by hlechner** [comment]
- How many video files belongs to this video file collection?
- If you restart the NDVM it show some of the videos added?
- Before the debug messages that you showed, there are more message? It seems that will be helpful to discover where it could be the last video added.

The wwidd has some code-design problem, sending everything at once, with a big amount of data (by having many videos), could be that problem. (see the issue is #16)

I must to add some additional debug information but troubleshooting it by adding the videos slowly instead of everything at once could help. you can move some files or just change the permission of the files/folders so the NDVM will not add it.

**Comment by hlechner** [comment]
About the folder issue: there is any peculiar letter: non-english or any different character on folder's name?
Maybe its conflicting with the name itself, I will do some tests trying to reproduce it.

Just make sure you try with the last code from this repo. on commit (9e1d7300fa0a2c091f0b968b1d6e2dcebb9459f5) I changed the walker to send only next sub-dir instead of 2 sub-dirs, it makes the difference in quantity.

**Comment by MikeSkril** [comment]
No special folder name, just 'Movies'.

With this commit in place it will walk only one directory deep, not going into sub folders?

**Comment by hlechner** [comment]
it goes, but it receive once at time, from the user perspective nothing changed.

**Comment by hlechner** [comment]
>The other issue seems to be related to the number of files. To reproduce you can create a folder with a few sub folders in it, putting like 60 video files in every sub folder. Now try to browse the folder, when you click on the plus symbol, it'll keeps spinning a long time before you can browse the folder. Sometimes 'walker' seemed to have died and not going on anymore.

I added it on a folder with 130 video files and with subfolders. and also I tried with a parent folder. but seems it's ok to me.

Did you have tested it with the lasted code from this repo? if not please try it.

**Comment by MikeSkril** [comment]
I'm still getting this error, but not always.
Here the directory structure:

Folder Movies - there are 8 sub directories - around 40 files in each sub folder 

It happens when I choose the whole folder 'Movies' and click ok. But as I said, not all the time.

**Comment by hlechner** [comment]
Let me know if this issue is solved by the last commit.

**Comment by hlechner** [comment]
@MikeSkril , could you give a feedback from this issue? If you still facing it

**Comment by MikeSkril** [comment]
I did not get the same error, but ffprobe was looping over the files over and over again.

**Comment by hlechner** [comment]
On this issue you've reported some errors/behaviors that I need to know if any are fixed now:

- [X] error: ``ERROR: TypeError: Cannot read property 'rootid' of undefined``
- [ ] no file added when selected the parent directory (Movies)
- [ ] after a ``Invalid Video file`` message no further messages of valid/invalid files
- [ ] on browser: when click on [+] on side of the folder's name it sometimes do not update, just keep waiting forever (before click on OK button)
- [ ] repeat the valid/invalid messages for the same files forever


based on your last comment seems that you're not facing the report 1: error message

I need to ask you these questions:
- the report 3 and 5 seems to be in conflict, any of them are not happening anymore?
- the report 4 still happening?


Also, It's very hard to find the cause of this issue without a properly log, I would ask you to start a new NDVM get the issue and copy all the information from the console. You can add it on gist (https://gist.github.com/) or a pastebin service. feel free to remove any filename or path from log if you find it necessary.


I tried different files and environments and even more files than you said that you're importing but I've found no issue here.

**Comment by MikeSkril** [comment]
Seems to be working now.
