### ISSUE TITLE
Cannot run start.sh

### ISSUE THREAD

**Issue by MikeSkril** [NDVM/NDVM#26]
I get below error when starting the last build.

- I'm running `start.sh` from the command line
- Node version 4.2.6
- I did not change anything before running the code
- I've downloaded the latest version here [https://github.com/NDVM/NDVM/archive/master.zip](url)
- the old version (from May15) is still running without issues

```
var debug = function debugMsg(msg, debugmsg = true, stdout = false) {
                                            ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/linux/New/NDVM-master/server/utils/walker.js:11:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

**Comment by hlechner** [comment]
Thanks for the information.

I must say that its better to use git to copy the files instead of using the zip generated by the github, I'm not sure if this zip can handle the symlinks files.

To full copy the repository is simple, you just need to use the following command:
```
git clone https://github.com/NDVM/NDVM.git
```

So, you can ``cd`` for whatever you want and then execute that command, it will copy the entire NDVM to the current directory.

I believe it could be the issue. Could you try it and let me know if it works?

**Comment by hlechner** [comment]
Ok, I reproduced the issue.

Seems that its fine on node.js 7.10.0 but not on 4.2.6.

**Comment by hlechner** [comment]
Commit sent, could you try it please?

**Comment by MikeSkril** [comment]
I had no chance to test it under the same environment as yesterday, but I've tried with node version 4.2.6 on another system and it looks good.

Thanks a lot for the fix!

```
user@8ece561e967b:/projects/NDVM$ ./start.sh
[INFO] Node.JS version: v4.2.6
[OK] Executing NDVM ...
[OK] Node.JS return:

Server running at http://127.0.0.1:7519
Browser started.
```
